package tw.com.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEPT.DID
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private Short did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_DEPT.DEPT_NAME
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEPT.DID
     *
     * @return the value of T_DEPT.DID
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public Short getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEPT.DID
     *
     * @param did the value for T_DEPT.DID
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setDid(Short did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_DEPT.DEPT_NAME
     *
     * @return the value of T_DEPT.DEPT_NAME
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_DEPT.DEPT_NAME
     *
     * @param deptName the value for T_DEPT.DEPT_NAME
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}