package tw.com.mybatis.pojo;

public class Emp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMP.EID
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private Short eid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMP.EMP_NAME
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMP.AGE
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private Short age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMP.SEX
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMP.EMAIL
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_EMP.DID
     *
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    private Short did;

    public Emp() {
    }

    public Emp(Short eid, String empName, Short age, String sex, String email, Short did) {
        this.eid = eid;
        this.empName = empName;
        this.age = age;
        this.sex = sex;
        this.email = email;
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMP.EID
     *
     * @return the value of T_EMP.EID
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public Short getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMP.EID
     *
     * @param eid the value for T_EMP.EID
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setEid(Short eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMP.EMP_NAME
     *
     * @return the value of T_EMP.EMP_NAME
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMP.EMP_NAME
     *
     * @param empName the value for T_EMP.EMP_NAME
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMP.AGE
     *
     * @return the value of T_EMP.AGE
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public Short getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMP.AGE
     *
     * @param age the value for T_EMP.AGE
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setAge(Short age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMP.SEX
     *
     * @return the value of T_EMP.SEX
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMP.SEX
     *
     * @param sex the value for T_EMP.SEX
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMP.EMAIL
     *
     * @return the value of T_EMP.EMAIL
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMP.EMAIL
     *
     * @param email the value for T_EMP.EMAIL
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_EMP.DID
     *
     * @return the value of T_EMP.DID
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public Short getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_EMP.DID
     *
     * @param did the value for T_EMP.DID
     * @mbggenerated Fri Jul 01 20:35:36 CST 2022
     */
    public void setDid(Short did) {
        this.did = did;
    }

    @Override
    public String toString() {
        return "Emp{" +
                "eid=" + eid +
                ", empName='" + empName + '\'' +
                ", age=" + age +
                ", sex='" + sex + '\'' +
                ", email='" + email + '\'' +
                ", did=" + did +
                '}';
    }
}